//! SQL keyword/operator -> token-type table.
//!
//! MECHANICALLY GENERATED from libinjection's `sql_keywords[]` in
//! `src/libinjection_sqli_data.h` (the fingerprint `'F'` entries, which all
//! start with `0`, are intentionally excluded -- those are handled by the
//! fingerprint `HashSet`). Do not edit by hand; see `data/ATTRIBUTION.md`.
//!
//! Entries are kept in the SAME order as the C array (ASCII byte order of the
//! upper-cased word), so a binary search reproduces libinjection's
//! `bsearch_keyword_type` exactly.

/// `(UPPERCASE_WORD, type_byte)` pairs, sorted by ASCII byte order of the word.
pub(crate) static SQL_KEYWORDS: &[(&str, u8)] = &[
    ("!!", b'o'),
    ("!<", b'o'),
    ("!=", b'o'),
    ("!>", b'o'),
    ("%=", b'o'),
    ("&&", b'&'),
    ("&=", b'o'),
    ("*=", b'o'),
    ("+=", b'o'),
    ("-=", b'o'),
    ("/=", b'o'),
    ("::", b'o'),
    (":=", b'o'),
    ("<<", b'o'),
    ("<=", b'o'),
    ("<>", b'o'),
    ("<@", b'o'),
    (">=", b'o'),
    (">>", b'o'),
    ("@>", b'o'),
    ("ABORT", b'k'),
    ("ABS", b'f'),
    ("ACCESSIBLE", b'k'),
    ("ACOS", b'f'),
    ("ADDDATE", b'f'),
    ("ADDTIME", b'f'),
    ("AES_DECRYPT", b'f'),
    ("AES_ENCRYPT", b'f'),
    ("AGAINST", b'k'),
    ("AGE", b'f'),
    ("ALL_USERS", b'k'),
    ("ALTER", b'k'),
    ("ALTER DOMAIN", b'k'),
    ("ALTER TABLE", b'k'),
    ("ANALYZE", b'k'),
    ("AND", b'&'),
    ("ANY", b'f'),
    ("ANYARRAY", b't'),
    ("ANYELEMENT", b't'),
    ("ANYNONARRY", b't'),
    ("APPLOCK_MODE", b'f'),
    ("APPLOCK_TEST", b'f'),
    ("APP_NAME", b'f'),
    ("ARRAY_AGG", b'f'),
    ("ARRAY_CAT", b'f'),
    ("ARRAY_DIM", b'f'),
    ("ARRAY_FILL", b'f'),
    ("ARRAY_LENGTH", b'f'),
    ("ARRAY_LOWER", b'f'),
    ("ARRAY_NDIMS", b'f'),
    ("ARRAY_PREPEND", b'f'),
    ("ARRAY_TO_JSON", b'f'),
    ("ARRAY_TO_STRING", b'f'),
    ("ARRAY_UPPER", b'f'),
    ("AS", b'k'),
    ("ASC", b'k'),
    ("ASCII", b'f'),
    ("ASENSITIVE", b'k'),
    ("ASIN", b'f'),
    ("ASSEMBLYPROPERTY", b'f'),
    ("ASYMKEY_ID", b'f'),
    ("AT TIME", b'n'),
    ("AT TIME ZONE", b'k'),
    ("ATAN", b'f'),
    ("ATAN2", b'f'),
    ("AUTOINCREMENT", b'k'),
    ("AVG", b'f'),
    ("BEFORE", b'k'),
    ("BEGIN", b'T'),
    ("BEGIN DECLARE", b'T'),
    ("BEGIN GOTO", b'T'),
    ("BEGIN TRY", b'T'),
    ("BEGIN TRY DECLARE", b'T'),
    ("BENCHMARK", b'f'),
    ("BETWEEN", b'o'),
    ("BIGINT", b't'),
    ("BIGSERIAL", b't'),
    ("BIN", b'f'),
    ("BINARY", b't'),
    ("BINARY_DOUBLE_INFINITY", b'1'),
    ("BINARY_DOUBLE_NAN", b'1'),
    ("BINARY_FLOAT_INFINITY", b'1'),
    ("BINARY_FLOAT_NAN", b'1'),
    ("BINBINARY", b'f'),
    ("BIT_AND", b'f'),
    ("BIT_COUNT", b'f'),
    ("BIT_LENGTH", b'f'),
    ("BIT_OR", b'f'),
    ("BIT_XOR", b'f'),
    ("BLOB", b'k'),
    ("BOOLEAN", b't'),
    ("BOOL_AND", b'f'),
    ("BOOL_OR", b'f'),
    ("BOTH", b'k'),
    ("BTRIM", b'f'),
    ("BY", b'n'),
    ("BYTEA", b't'),
    ("CALL", b'T'),
    ("CASCADE", b'k'),
    ("CASE", b'E'),
    ("CAST", b'f'),
    ("CBOOL", b'f'),
    ("CBRT", b'f'),
    ("CBYTE", b'f'),
    ("CCUR", b'f'),
    ("CDATE", b'f'),
    ("CDBL", b'f'),
    ("CEIL", b'f'),
    ("CEILING", b'f'),
    ("CERTENCODED", b'f'),
    ("CERTPRIVATEKEY", b'f'),
    ("CERT_ID", b'f'),
    ("CERT_PROPERTY", b'f'),
    ("CHANGE", b'k'),
    ("CHANGES", b'f'),
    ("CHAR", b'f'),
    ("CHARACTER", b't'),
    ("CHARACTER VARYING", b't'),
    ("CHARACTER_LENGTH", b'f'),
    ("CHARINDEX", b'f'),
    ("CHARSET", b'f'),
    ("CHAR_LENGTH", b'f'),
    ("CHDIR", b'f'),
    ("CHDRIVE", b'f'),
    ("CHECK", b'n'),
    ("CHECKSUM_AGG", b'f'),
    ("CHOOSE", b'f'),
    ("CHR", b'f'),
    ("CINT", b'f'),
    ("CLNG", b'f'),
    ("CLOCK_TIMESTAMP", b'f'),
    ("COALESCE", b'f'),
    ("COERCIBILITY", b'f'),
    ("COLLATE", b'A'),
    ("COLLATION", b'f'),
    ("COLLATIONPROPERTY", b'f'),
    ("COLUMN", b'k'),
    ("COLUMNPROPERTY", b'f'),
    ("COLUMNS_UPDATED", b'f'),
    ("COL_LENGTH", b'f'),
    ("COL_NAME", b'f'),
    ("COMPRESS", b'f'),
    ("CONCAT", b'f'),
    ("CONCAT_WS", b'f'),
    ("CONDITION", b'k'),
    ("CONNECTION_ID", b'f'),
    ("CONSTRAINT", b'k'),
    ("CONTINUE", b'k'),
    ("CONV", b'f'),
    ("CONVERT", b'f'),
    ("CONVERT_FROM", b'f'),
    ("CONVERT_TO", b'f'),
    ("CONVERT_TZ", b'f'),
    ("COS", b'f'),
    ("COT", b'f'),
    ("COUNT", b'f'),
    ("COUNT_BIG", b'k'),
    ("CRC32", b'f'),
    ("CREATE", b'E'),
    ("CREATE OR", b'n'),
    ("CREATE OR REPLACE", b'T'),
    ("CROSS", b'n'),
    ("CROSS JOIN", b'k'),
    ("CSNG", b'f'),
    ("CSTRING", b't'),
    ("CTXSYS.DRITHSX.SN", b'f'),
    ("CUME_DIST", b'f'),
    ("CURDATE", b'f'),
    ("CURDIR", b'f'),
    ("CURRENT DATE", b'v'),
    ("CURRENT DEGREE", b'v'),
    ("CURRENT FUNCTION", b'v'),
    ("CURRENT FUNCTION PATH", b'v'),
    ("CURRENT PATH", b'v'),
    ("CURRENT SCHEMA", b'v'),
    ("CURRENT SERVER", b'v'),
    ("CURRENT TIME", b'v'),
    ("CURRENT TIMEZONE", b'v'),
    ("CURRENTUSER", b'f'),
    ("CURRENT_DATABASE", b'f'),
    ("CURRENT_DATE", b'v'),
    ("CURRENT_PATH", b'v'),
    ("CURRENT_QUERY", b'f'),
    ("CURRENT_SCHEMA", b'f'),
    ("CURRENT_SCHEMAS", b'f'),
    ("CURRENT_SERVER", b'v'),
    ("CURRENT_SETTING", b'f'),
    ("CURRENT_TIME", b'v'),
    ("CURRENT_TIMESTAMP", b'v'),
    ("CURRENT_TIMEZONE", b'v'),
    ("CURRENT_USER", b'v'),
    ("CURRVAL", b'f'),
    ("CURSOR", b'k'),
    ("CURSOR_STATUS", b'f'),
    ("CURTIME", b'f'),
    ("CVAR", b'f'),
    ("DATABASE", b'n'),
    ("DATABASEPROPERTYEX", b'f'),
    ("DATABASES", b'k'),
    ("DATABASE_PRINCIPAL_ID", b'f'),
    ("DATALENGTH", b'f'),
    ("DATE", b'f'),
    ("DATEADD", b'f'),
    ("DATEDIFF", b'f'),
    ("DATEFROMPARTS", b'f'),
    ("DATENAME", b'f'),
    ("DATEPART", b'f'),
    ("DATESERIAL", b'f'),
    ("DATETIME2FROMPARTS", b'f'),
    ("DATETIMEFROMPARTS", b'f'),
    ("DATETIMEOFFSETFROMPARTS", b'f'),
    ("DATEVALUE", b'f'),
    ("DATE_ADD", b'f'),
    ("DATE_FORMAT", b'f'),
    ("DATE_PART", b'f'),
    ("DATE_SUB", b'f'),
    ("DATE_TRUNC", b'f'),
    ("DAVG", b'f'),
    ("DAY", b'f'),
    ("DAYNAME", b'f'),
    ("DAYOFMONTH", b'f'),
    ("DAYOFWEEK", b'f'),
    ("DAYOFYEAR", b'f'),
    ("DAY_HOUR", b'k'),
    ("DAY_MICROSECOND", b'k'),
    ("DAY_MINUTE", b'k'),
    ("DAY_SECOND", b'k'),
    ("DBMS_LOCK.SLEEP", b'f'),
    ("DBMS_PIPE.RECEIVE_MESSAGE", b'f'),
    ("DBMS_UTILITY.SQLID_TO_SQLHASH", b'f'),
    ("DB_ID", b'f'),
    ("DB_NAME", b'f'),
    ("DCOUNT", b'f'),
    ("DEC", b'k'),
    ("DECIMAL", b't'),
    ("DECLARE", b'T'),
    ("DECODE", b'f'),
    ("DECRYPTBYASMKEY", b'f'),
    ("DECRYPTBYCERT", b'f'),
    ("DECRYPTBYKEY", b'f'),
    ("DECRYPTBYKEYAUTOCERT", b'f'),
    ("DECRYPTBYPASSPHRASE", b'f'),
    ("DEFAULT", b'k'),
    ("DEGREES", b'f'),
    ("DELAY", b'k'),
    ("DELAYED", b'k'),
    ("DELETE", b'T'),
    ("DENSE_RANK", b'f'),
    ("DESC", b'k'),
    ("DESCRIBE", b'k'),
    ("DES_DECRYPT", b'f'),
    ("DES_ENCRYPT", b'f'),
    ("DETERMINISTIC", b'k'),
    ("DFIRST", b'f'),
    ("DIFFERENCE", b'f'),
    ("DISTINCT", b'k'),
    ("DISTINCTROW", b'k'),
    ("DIV", b'o'),
    ("DLAST", b'f'),
    ("DLOOKUP", b'f'),
    ("DMAX", b'f'),
    ("DMIN", b'f'),
    ("DO", b'n'),
    ("DOUBLE", b't'),
    ("DOUBLE PRECISION", b't'),
    ("DROP", b'T'),
    ("DSUM", b'f'),
    ("DUAL", b'n'),
    ("EACH", b'k'),
    ("ELSE", b'k'),
    ("ELSEIF", b'k'),
    ("ELT", b'f'),
    ("ENCLOSED", b'k'),
    ("ENCODE", b'f'),
    ("ENCRYPT", b'f'),
    ("ENCRYPTBYASMKEY", b'f'),
    ("ENCRYPTBYCERT", b'f'),
    ("ENCRYPTBYKEY", b'f'),
    ("ENCRYPTBYPASSPHRASE", b'f'),
    ("ENUM_FIRST", b'f'),
    ("ENUM_LAST", b'f'),
    ("ENUM_RANGE", b'f'),
    ("EOMONTH", b'f'),
    ("EQV", b'o'),
    ("ESCAPED", b'k'),
    ("EVENTDATA", b'f'),
    ("EXCEPT", b'U'),
    ("EXEC", b'T'),
    ("EXECUTE", b'T'),
    ("EXECUTE AS", b'E'),
    ("EXECUTE AS LOGIN", b'E'),
    ("EXISTS", b'f'),
    ("EXIT", b'k'),
    ("EXP", b'f'),
    ("EXPLAIN", b'k'),
    ("EXPORT_SET", b'f'),
    ("EXTRACT", b'f'),
    ("EXTRACTVALUE", b'f'),
    ("EXTRACT_VALUE", b'f'),
    ("FALSE", b'1'),
    ("FETCH", b'k'),
    ("FIELD", b'f'),
    ("FILEDATETIME", b'f'),
    ("FILEGROUPPROPERTY", b'f'),
    ("FILEGROUP_ID", b'f'),
    ("FILEGROUP_NAME", b'f'),
    ("FILELEN", b'f'),
    ("FILEPROPERTY", b'f'),
    ("FILETOBLOB", b'f'),
    ("FILETOCLOB", b'f'),
    ("FILE_ID", b'f'),
    ("FILE_IDEX", b'f'),
    ("FILE_NAME", b'f'),
    ("FIND_IN_SET", b'f'),
    ("FIRST_VALUE", b'f'),
    ("FLOAT", b't'),
    ("FLOAT4", b't'),
    ("FLOAT8", b't'),
    ("FLOOR", b'f'),
    ("FN_VIRTUALFILESTATS", b'f'),
    ("FOR", b'n'),
    ("FOR UPDATE", b'k'),
    ("FOR UPDATE NOWAIT", b'k'),
    ("FOR UPDATE OF", b'k'),
    ("FOR UPDATE SKIP", b'k'),
    ("FOR UPDATE SKIP LOCKED", b'k'),
    ("FOR UPDATE WAIT", b'k'),
    ("FORCE", b'k'),
    ("FOREIGN", b'k'),
    ("FORMAT", b'f'),
    ("FOUND_ROWS", b'f'),
    ("FROM", b'k'),
    ("FROM_BASE64", b'f'),
    ("FROM_DAYS", b'f'),
    ("FROM_UNIXTIME", b'f'),
    ("FULL JOIN", b'k'),
    ("FULL OUTER", b'k'),
    ("FULL OUTER JOIN", b'k'),
    ("FULLTEXT", b'k'),
    ("FULLTEXTCATALOGPROPERTY", b'f'),
    ("FULLTEXTSERVICEPROPERTY", b'f'),
    ("FUNCTION", b'k'),
    ("GENERATE_SERIES", b'f'),
    ("GENERATE_SUBSCRIPTS", b'f'),
    ("GETATTR", b'f'),
    ("GETDATE", b'f'),
    ("GETUTCDATE", b'f'),
    ("GET_BIT", b'f'),
    ("GET_BYTE", b'f'),
    ("GET_FORMAT", b'f'),
    ("GET_LOCK", b'f'),
    ("GO", b'T'),
    ("GOTO", b'T'),
    ("GRANT", b'k'),
    ("GREATEST", b'f'),
    ("GROUP", b'n'),
    ("GROUP BY", b'B'),
    ("GROUPING", b'f'),
    ("GROUPING_ID", b'f'),
    ("GROUP_CONCAT", b'f'),
    ("HANDLER", b'T'),
    ("HASHBYTES", b'f'),
    ("HAS_PERMS_BY_NAME", b'f'),
    ("HAVING", b'B'),
    ("HEX", b'f'),
    ("HIGH_PRIORITY", b'k'),
    ("HOST_NAME", b'f'),
    ("HOUR", b'f'),
    ("HOUR_MICROSECOND", b'k'),
    ("HOUR_MINUTE", b'k'),
    ("HOUR_SECOND", b'k'),
    ("IDENTIFY", b'f'),
    ("IDENT_CURRENT", b'f'),
    ("IDENT_INCR", b'f'),
    ("IDENT_SEED", b'f'),
    ("IF", b'f'),
    ("IF EXISTS", b'f'),
    ("IF NOT", b'f'),
    ("IF NOT EXISTS", b'f'),
    ("IFF", b'f'),
    ("IFNULL", b'f'),
    ("IGNORE", b'k'),
    ("IIF", b'f'),
    ("IN", b'k'),
    ("IN BOOLEAN", b'n'),
    ("IN BOOLEAN MODE", b'k'),
    ("INDEX", b'k'),
    ("INDEXKEY_PROPERTY", b'f'),
    ("INDEXPROPERTY", b'f'),
    ("INDEX_COL", b'f'),
    ("INET_ATON", b'f'),
    ("INET_NTOA", b'f'),
    ("INFILE", b'k'),
    ("INITCAP", b'f'),
    ("INNER", b'k'),
    ("INNER JOIN", b'k'),
    ("INOUT", b'k'),
    ("INSENSITIVE", b'k'),
    ("INSERT", b'E'),
    ("INSERT DELAYED", b'E'),
    ("INSERT DELAYED INTO", b'T'),
    ("INSERT HIGH_PRIORITY", b'E'),
    ("INSERT HIGH_PRIORITY INTO", b'T'),
    ("INSERT IGNORE", b'E'),
    ("INSERT IGNORE INTO", b'T'),
    ("INSERT INTO", b'T'),
    ("INSERT LOW_PRIORITY", b'E'),
    ("INSERT LOW_PRIORITY INTO", b'T'),
    ("INSTR", b'f'),
    ("INSTRREV", b'f'),
    ("INT", b't'),
    ("INT1", b't'),
    ("INT2", b't'),
    ("INT3", b't'),
    ("INT4", b't'),
    ("INT8", b't'),
    ("INTEGER", b't'),
    ("INTERSECT", b'U'),
    ("INTERSECT ALL", b'U'),
    ("INTERVAL", b'k'),
    ("INTO", b'k'),
    ("INTO DUMPFILE", b'k'),
    ("INTO OUTFILE", b'k'),
    ("IS", b'o'),
    ("IS DISTINCT", b'n'),
    ("IS DISTINCT FROM", b'o'),
    ("IS NOT", b'o'),
    ("IS NOT DISTINCT", b'n'),
    ("IS NOT DISTINCT FROM", b'o'),
    ("ISDATE", b'f'),
    ("ISEMPTY", b'f'),
    ("ISFINITE", b'f'),
    ("ISNULL", b'f'),
    ("ISNUMERIC", b'f'),
    ("IS_FREE_LOCK", b'f'),
    ("IS_MEMBER", b'f'),
    ("IS_OBJECTSIGNED", b'f'),
    ("IS_ROLEMEMBER", b'f'),
    ("IS_SRVROLEMEMBER", b'f'),
    ("IS_USED_LOCK", b'f'),
    ("ITERATE", b'k'),
    ("JOIN", b'k'),
    ("JSON_KEYS", b'f'),
    ("JULIANDAY", b'f'),
    ("JUSTIFY_DAYS", b'f'),
    ("JUSTIFY_HOURS", b'f'),
    ("JUSTIFY_INTERVAL", b'f'),
    ("KEYS", b'k'),
    ("KEY_GUID", b'f'),
    ("KEY_ID", b'f'),
    ("KILL", b'k'),
    ("LAG", b'f'),
    ("LASTVAL", b'f'),
    ("LAST_INSERT_ID", b'f'),
    ("LAST_INSERT_ROWID", b'f'),
    ("LAST_VALUE", b'f'),
    ("LCASE", b'f'),
    ("LEAD", b'f'),
    ("LEADING", b'k'),
    ("LEAST", b'f'),
    ("LEAVE", b'k'),
    ("LEFT", b'f'),
    ("LEFT JOIN", b'k'),
    ("LEFT OUTER", b'k'),
    ("LEFT OUTER JOIN", b'k'),
    ("LENGTH", b'f'),
    ("LIKE", b'o'),
    ("LIMIT", b'B'),
    ("LINEAR", b'k'),
    ("LINES", b'k'),
    ("LN", b'f'),
    ("LOAD", b'k'),
    ("LOAD DATA", b'T'),
    ("LOAD XML", b'T'),
    ("LOAD_EXTENSION", b'f'),
    ("LOAD_FILE", b'f'),
    ("LOCALTIME", b'v'),
    ("LOCALTIMESTAMP", b'v'),
    ("LOCATE", b'f'),
    ("LOCK", b'n'),
    ("LOCK IN", b'n'),
    ("LOCK IN SHARE", b'n'),
    ("LOCK IN SHARE MODE", b'k'),
    ("LOCK TABLE", b'k'),
    ("LOCK TABLES", b'k'),
    ("LOG", b'f'),
    ("LOG10", b'f'),
    ("LOG2", b'f'),
    ("LONGBLOB", b'k'),
    ("LONGTEXT", b'k'),
    ("LOOP", b'k'),
    ("LOWER", b'f'),
    ("LOWER_INC", b'f'),
    ("LOWER_INF", b'f'),
    ("LOW_PRIORITY", b'k'),
    ("LPAD", b'f'),
    ("LTRIM", b'f'),
    ("MAKEDATE", b'f'),
    ("MAKE_SET", b'f'),
    ("MASKLEN", b'f'),
    ("MASTER_BIND", b'k'),
    ("MASTER_POS_WAIT", b'f'),
    ("MASTER_SSL_VERIFY_SERVER_CERT", b'k'),
    ("MATCH", b'k'),
    ("MAX", b'f'),
    ("MAXVALUE", b'k'),
    ("MD5", b'f'),
    ("MEDIUMBLOB", b'k'),
    ("MEDIUMINT", b'k'),
    ("MEDIUMTEXT", b'k'),
    ("MERGE", b'k'),
    ("MICROSECOND", b'f'),
    ("MID", b'f'),
    ("MIDDLEINT", b'k'),
    ("MIN", b'f'),
    ("MINUTE", b'f'),
    ("MINUTE_MICROSECOND", b'k'),
    ("MINUTE_SECOND", b'k'),
    ("MKDIR", b'f'),
    ("MOD", b'o'),
    ("MODE", b'n'),
    ("MODIFIES", b'k'),
    ("MONEY", b't'),
    ("MONTH", b'f'),
    ("MONTHNAME", b'f'),
    ("NAME_CONST", b'f'),
    ("NATURAL", b'n'),
    ("NATURAL FULL", b'k'),
    ("NATURAL FULL OUTER JOIN", b'k'),
    ("NATURAL INNER", b'k'),
    ("NATURAL JOIN", b'k'),
    ("NATURAL LEFT", b'k'),
    ("NATURAL LEFT OUTER", b'k'),
    ("NATURAL LEFT OUTER JOIN", b'k'),
    ("NATURAL OUTER", b'k'),
    ("NATURAL RIGHT", b'k'),
    ("NATURAL RIGHT OUTER JOIN", b'k'),
    ("NETMASK", b'f'),
    ("NEXT VALUE", b'n'),
    ("NEXT VALUE FOR", b'k'),
    ("NEXTVAL", b'f'),
    ("NOT", b'o'),
    ("NOT BETWEEN", b'o'),
    ("NOT IN", b'k'),
    ("NOT LIKE", b'o'),
    ("NOT REGEXP", b'o'),
    ("NOT RLIKE", b'o'),
    ("NOT SIMILAR", b'o'),
    ("NOT SIMILAR TO", b'o'),
    ("NOTNULL", b'k'),
    ("NOW", b'f'),
    ("NOWAIT", b'k'),
    ("NO_WRITE_TO_BINLOG", b'k'),
    ("NTH_VALUE", b'f'),
    ("NTILE", b'f'),
    ("NULL", b'v'),
    ("NULLIF", b'f'),
    ("NUMERIC", b't'),
    ("NZ", b'f'),
    ("OBJECTPROPERTY", b'f'),
    ("OBJECTPROPERTYEX", b'f'),
    ("OBJECT_DEFINITION", b'f'),
    ("OBJECT_ID", b'f'),
    ("OBJECT_NAME", b'f'),
    ("OBJECT_SCHEMA_NAME", b'f'),
    ("OCT", b'f'),
    ("OCTET_LENGTH", b'f'),
    ("OFFSET", b'k'),
    ("OID", b't'),
    ("OLD_PASSWORD", b'f'),
    ("ONE_SHOT", b'k'),
    ("OPEN", b'k'),
    ("OPENDATASOURCE", b'f'),
    ("OPENQUERY", b'f'),
    ("OPENROWSET", b'f'),
    ("OPENXML", b'f'),
    ("OPTIMIZE", b'k'),
    ("OPTION", b'k'),
    ("OPTIONALLY", b'k'),
    ("OR", b'&'),
    ("ORD", b'f'),
    ("ORDER", b'n'),
    ("ORDER BY", b'B'),
    ("ORIGINAL_DB_NAME", b'f'),
    ("ORIGINAL_LOGIN", b'f'),
    ("OUT", b'n'),
    ("OUTER", b'n'),
    ("OUTFILE", b'k'),
    ("OVERLAPS", b'f'),
    ("OVERLAY", b'f'),
    ("OWN3D", b'k'),
    ("OWN3D BY", b'B'),
    ("PARSENAME", b'f'),
    ("PARTITION", b'k'),
    ("PARTITION BY", b'B'),
    ("PASSWORD", b'n'),
    ("PATHINDEX", b'f'),
    ("PATINDEX", b'f'),
    ("PERCENTILE_COUNT", b'f'),
    ("PERCENTILE_DISC", b'f'),
    ("PERCENTILE_RANK", b'f'),
    ("PERCENT_RANK", b'f'),
    ("PERIOD_ADD", b'f'),
    ("PERIOD_DIFF", b'f'),
    ("PERMISSIONS", b'f'),
    ("PG_ADVISORY_LOCK", b'f'),
    ("PG_BACKEND_PID", b'f'),
    ("PG_CANCEL_BACKEND", b'f'),
    ("PG_CLIENT_ENCODING", b'f'),
    ("PG_CONF_LOAD_TIME", b'f'),
    ("PG_CREATE_RESTORE_POINT", b'f'),
    ("PG_HAS_ROLE", b'f'),
    ("PG_IS_IN_RECOVERY", b'f'),
    ("PG_IS_OTHER_TEMP_SCHEMA", b'f'),
    ("PG_LISTENING_CHANNELS", b'f'),
    ("PG_LS_DIR", b'f'),
    ("PG_MY_TEMP_SCHEMA", b'f'),
    ("PG_POSTMASTER_START_TIME", b'f'),
    ("PG_READ_BINARY_FILE", b'f'),
    ("PG_READ_FILE", b'f'),
    ("PG_RELOAD_CONF", b'f'),
    ("PG_ROTATE_LOGFILE", b'f'),
    ("PG_SLEEP", b'f'),
    ("PG_START_BACKUP", b'f'),
    ("PG_STAT_FILE", b'f'),
    ("PG_STOP_BACKUP", b'f'),
    ("PG_SWITCH_XLOG", b'f'),
    ("PG_TERMINATE_BACKEND", b'f'),
    ("PG_TRIGGER_DEPTH", b'f'),
    ("PI", b'f'),
    ("POSITION", b'f'),
    ("POW", b'f'),
    ("POWER", b'f'),
    ("PRECISION", b'k'),
    ("PREVIOUS VALUE", b'n'),
    ("PREVIOUS VALUE FOR", b'k'),
    ("PRIMARY", b'k'),
    ("PRINT", b'T'),
    ("PROCEDURE", b'k'),
    ("PROCEDURE ANALYSE", b'f'),
    ("PUBLISHINGSERVERNAME", b'f'),
    ("PURGE", b'k'),
    ("PWDCOMPARE", b'f'),
    ("PWDENCRYPT", b'f'),
    ("QUARTER", b'f'),
    ("QUOTE", b'f'),
    ("QUOTENAME", b'f'),
    ("QUOTE_IDENT", b'f'),
    ("QUOTE_LITERAL", b'f'),
    ("QUOTE_NULLABLE", b'f'),
    ("RADIANS", b'f'),
    ("RAISEERROR", b'E'),
    ("RAND", b'f'),
    ("RANDOM", b'f'),
    ("RANDOMBLOB", b'f'),
    ("RANGE", b'k'),
    ("RANK", b'f'),
    ("READ", b'k'),
    ("READ WRITE", b'k'),
    ("READS", b'k'),
    ("READ_WRITE", b'k'),
    ("REAL", b't'),
    ("REFERENCES", b'k'),
    ("REGCLASS", b't'),
    ("REGCONFIG", b't'),
    ("REGDICTIONARY", b't'),
    ("REGEXP", b'o'),
    ("REGEXP_INSTR", b'f'),
    ("REGEXP_MATCHES", b'f'),
    ("REGEXP_REPLACE", b'f'),
    ("REGEXP_SPLIT_TO_ARRAY", b'f'),
    ("REGEXP_SPLIT_TO_TABLE", b'f'),
    ("REGEXP_SUBSTR", b'f'),
    ("REGOPER", b't'),
    ("REGOPERATOR", b't'),
    ("REGPROC", b't'),
    ("REGPROCEDURE", b't'),
    ("REGTYPE", b't'),
    ("RELEASE", b'k'),
    ("RELEASE_LOCK", b'f'),
    ("RENAME", b'k'),
    ("REPEAT", b'k'),
    ("REPLACE", b'k'),
    ("REPLICATE", b'f'),
    ("REQUIRE", b'k'),
    ("RESIGNAL", b'k'),
    ("RESTRICT", b'k'),
    ("RETURN", b'k'),
    ("REVERSE", b'f'),
    ("REVOKE", b'k'),
    ("RIGHT", b'n'),
    ("RIGHT JOIN", b'k'),
    ("RIGHT OUTER", b'k'),
    ("RIGHT OUTER JOIN", b'k'),
    ("RLIKE", b'o'),
    ("ROUND", b'f'),
    ("ROW", b'f'),
    ("ROW_COUNT", b'f'),
    ("ROW_NUMBER", b'f'),
    ("ROW_TO_JSON", b'f'),
    ("RPAD", b'f'),
    ("RTRIM", b'f'),
    ("SCHAMA_NAME", b'f'),
    ("SCHEMA", b'k'),
    ("SCHEMAS", b'k'),
    ("SCHEMA_ID", b'f'),
    ("SCOPE_IDENTITY", b'f'),
    ("SECOND_MICROSECOND", b'k'),
    ("SEC_TO_TIME", b'f'),
    ("SELECT", b'E'),
    ("SELECT ALL", b'E'),
    ("SELECT DISTINCT", b'E'),
    ("SENSITIVE", b'k'),
    ("SEPARATOR", b'k'),
    ("SERIAL", b't'),
    ("SERIAL2", b't'),
    ("SERIAL4", b't'),
    ("SERIAL8", b't'),
    ("SERVERPROPERTY", b'f'),
    ("SESSION_USER", b'f'),
    ("SET", b'E'),
    ("SETATTR", b'f'),
    ("SETSEED", b'f'),
    ("SETVAL", b'f'),
    ("SET_BIT", b'f'),
    ("SET_BYTE", b'f'),
    ("SET_CONFIG", b'f'),
    ("SET_MASKLEN", b'f'),
    ("SHA", b'f'),
    ("SHA1", b'f'),
    ("SHA2", b'f'),
    ("SHOW", b'n'),
    ("SHUTDOWN", b'T'),
    ("SIGN", b'f'),
    ("SIGNAL", b'k'),
    ("SIGNBYASMKEY", b'f'),
    ("SIGNBYCERT", b'f'),
    ("SIMILAR", b'k'),
    ("SIMILAR TO", b'o'),
    ("SIN", b'f'),
    ("SLEEP", b'f'),
    ("SMALLDATETIMEFROMPARTS", b'f'),
    ("SMALLINT", b't'),
    ("SMALLSERIAL", b't'),
    ("SOME", b'f'),
    ("SOUNDEX", b'f'),
    ("SOUNDS", b'o'),
    ("SOUNDS LIKE", b'o'),
    ("SPACE", b'f'),
    ("SPATIAL", b'k'),
    ("SPECIFIC", b'k'),
    ("SPLIT_PART", b'f'),
    ("SQL", b'k'),
    ("SQLEXCEPTION", b'k'),
    ("SQLITE_VERSION", b'f'),
    ("SQLSTATE", b'k'),
    ("SQLWARNING", b'k'),
    ("SQL_BIG_RESULT", b'k'),
    ("SQL_BUFFER_RESULT", b'k'),
    ("SQL_CACHE", b'k'),
    ("SQL_CALC_FOUND_ROWS", b'k'),
    ("SQL_NO_CACHE", b'k'),
    ("SQL_SMALL_RESULT", b'k'),
    ("SQL_VARIANT_PROPERTY", b'f'),
    ("SQRT", b'f'),
    ("SSL", b'k'),
    ("STARTING", b'k'),
    ("STATEMENT_TIMESTAMP", b'f'),
    ("STATS_DATE", b'f'),
    ("STDDEV", b'f'),
    ("STDDEV_POP", b'f'),
    ("STDDEV_SAMP", b'f'),
    ("STRAIGHT_JOIN", b'k'),
    ("STRCMP", b'f'),
    ("STRCOMP", b'f'),
    ("STRCONV", b'f'),
    ("STRING_AGG", b'f'),
    ("STRING_TO_ARRAY", b'f'),
    ("STRPOS", b'f'),
    ("STR_TO_DATE", b'f'),
    ("STUFF", b'f'),
    ("SUBDATE", b'f'),
    ("SUBSTR", b'f'),
    ("SUBSTRING", b'f'),
    ("SUBSTRING_INDEX", b'f'),
    ("SUBTIME", b'f'),
    ("SUM", b'f'),
    ("SUSER_ID", b'f'),
    ("SUSER_NAME", b'f'),
    ("SUSER_SID", b'f'),
    ("SUSER_SNAME", b'f'),
    ("SWITCHOFFET", b'f'),
    ("SYS.DATABASE_NAME", b'n'),
    ("SYS.FN_BUILTIN_PERMISSIONS", b'f'),
    ("SYS.FN_GET_AUDIT_FILE", b'f'),
    ("SYS.FN_MY_PERMISSIONS", b'f'),
    ("SYS.STRAGG", b'f'),
    ("SYSCOLUMNS", b'k'),
    ("SYSDATE", b'f'),
    ("SYSDATETIME", b'f'),
    ("SYSDATETIMEOFFSET", b'f'),
    ("SYSOBJECTS", b'k'),
    ("SYSTEM_USER", b'f'),
    ("SYSUSERS", b'k'),
    ("SYSUTCDATETME", b'f'),
    ("TABLE", b'n'),
    ("TAN", b'f'),
    ("TERMINATED", b'k'),
    ("TERTIARY_WEIGHTS", b'f'),
    ("TEXT", b't'),
    ("TEXTPOS", b'f'),
    ("TEXTPTR", b'f'),
    ("TEXTVALID", b'f'),
    ("THEN", b'k'),
    ("TIME", b'k'),
    ("TIMEDIFF", b'f'),
    ("TIMEFROMPARTS", b'f'),
    ("TIMEOFDAY", b'f'),
    ("TIMESERIAL", b'f'),
    ("TIMESTAMP", b't'),
    ("TIMESTAMPADD", b'f'),
    ("TIMEVALUE", b'f'),
    ("TIME_FORMAT", b'f'),
    ("TIME_TO_SEC", b'f'),
    ("TINYBLOB", b'k'),
    ("TINYINT", b'k'),
    ("TINYTEXT", b'k'),
    ("TODATETIMEOFFSET", b'f'),
    ("TOP", b'k'),
    ("TOTAL", b'f'),
    ("TOTAL_CHANGES", b'f'),
    ("TO_ASCII", b'f'),
    ("TO_BASE64", b'f'),
    ("TO_CHAR", b'f'),
    ("TO_DATE", b'f'),
    ("TO_DAYS", b'f'),
    ("TO_HEX", b'f'),
    ("TO_NUMBER", b'f'),
    ("TO_SECONDS", b'f'),
    ("TO_TIMESTAMP", b'f'),
    ("TRAILING", b'n'),
    ("TRANSACTION_TIMESTAMP", b'f'),
    ("TRANSLATE", b'f'),
    ("TRIGGER", b'k'),
    ("TRIGGER_NESTLEVEL", b'f'),
    ("TRIM", b'f'),
    ("TRUE", b'1'),
    ("TRUNC", b'f'),
    ("TRUNCATE", b'f'),
    ("TRY", b'T'),
    ("TRY_CAST", b'f'),
    ("TRY_CONVERT", b'f'),
    ("TRY_PARSE", b'f'),
    ("TYPEOF", b'f'),
    ("TYPEPROPERTY", b'f'),
    ("TYPE_ID", b'f'),
    ("TYPE_NAME", b'f'),
    ("UCASE", b'f'),
    ("UESCAPE", b'o'),
    ("UNCOMPRESS", b'f'),
    ("UNCOMPRESS_LENGTH", b'f'),
    ("UNDO", b'k'),
    ("UNHEX", b'f'),
    ("UNICODE", b'f'),
    ("UNION", b'U'),
    ("UNION ALL", b'U'),
    ("UNION ALL DISTINCT", b'U'),
    ("UNION DISTINCT", b'U'),
    ("UNION DISTINCT ALL", b'U'),
    ("UNIQUE", b'n'),
    ("UNIX_TIMESTAMP", b'f'),
    ("UNI_ON", b'U'),
    ("UNKNOWN", b'v'),
    ("UNLOCK", b'k'),
    ("UNNEST", b'f'),
    ("UNSIGNED", b'k'),
    ("UPDATE", b'E'),
    ("UPDATEXML", b'f'),
    ("UPPER", b'f'),
    ("UPPER_INC", b'f'),
    ("UPPER_INF", b'f'),
    ("USAGE", b'k'),
    ("USE", b'T'),
    ("USER", b'n'),
    ("USER_ID", b'n'),
    ("USER_LOCK.SLEEP", b'f'),
    ("USER_NAME", b'n'),
    ("USING", b'f'),
    ("UTC_DATE", b'k'),
    ("UTC_TIME", b'k'),
    ("UTC_TIMESTAMP", b'k'),
    ("UTL_HTTP.REQUEST", b'f'),
    ("UTL_INADDR.GET_HOST_ADDRESS", b'f'),
    ("UTL_INADDR.GET_HOST_NAME", b'f'),
    ("UUID", b'f'),
    ("UUID_SHORT", b'f'),
    ("VALUES", b'k'),
    ("VAR", b'f'),
    ("VARBINARY", b'k'),
    ("VARCHAR", b't'),
    ("VARCHARACTER", b'k'),
    ("VARIANCE", b'f'),
    ("VARP", b'f'),
    ("VARYING", b'k'),
    ("VAR_POP", b'f'),
    ("VAR_SAMP", b'f'),
    ("VERIFYSIGNEDBYASMKEY", b'f'),
    ("VERIFYSIGNEDBYCERT", b'f'),
    ("VERSION", b'f'),
    ("VOID", b't'),
    ("WAIT", b'k'),
    ("WAITFOR", b'n'),
    ("WAITFOR DELAY", b'E'),
    ("WAITFOR RECEIVE", b'E'),
    ("WAITFOR TIME", b'E'),
    ("WEEK", b'f'),
    ("WEEKDAY", b'f'),
    ("WEEKDAYNAME", b'f'),
    ("WEEKOFYEAR", b'f'),
    ("WHEN", b'k'),
    ("WHERE", b'k'),
    ("WHILE", b'T'),
    ("WIDTH_BUCKET", b'f'),
    ("WITH", b'n'),
    ("WITH ROLLUP", b'k'),
    ("XMLAGG", b'f'),
    ("XMLCOMMENT", b'f'),
    ("XMLCONCAT", b'f'),
    ("XMLELEMENT", b'f'),
    ("XMLEXISTS", b'f'),
    ("XMLFOREST", b'f'),
    ("XMLFORMAT", b'f'),
    ("XMLPI", b'f'),
    ("XMLROOT", b'f'),
    ("XMLTYPE", b'f'),
    ("XML_IS_WELL_FORMED", b'f'),
    ("XOR", b'&'),
    ("XPATH", b'f'),
    ("XPATH_EXISTS", b'f'),
    ("XP_EXECRESULTSET", b'k'),
    ("YEAR", b'f'),
    ("YEARWEEK", b'f'),
    ("YEAR_MONTH", b'k'),
    ("ZEROBLOB", b'f'),
    ("ZEROFILL", b'k'),
    ("^=", b'o'),
    ("_ARMSCII8", b't'),
    ("_ASCII", b't'),
    ("_BIG5", b't'),
    ("_BINARY", b't'),
    ("_CP1250", b't'),
    ("_CP1251", b't'),
    ("_CP1257", b't'),
    ("_CP850", b't'),
    ("_CP852", b't'),
    ("_CP866", b't'),
    ("_CP932", b't'),
    ("_DEC8", b't'),
    ("_EUCJPMS", b't'),
    ("_EUCKR", b't'),
    ("_GB2312", b't'),
    ("_GBK", b't'),
    ("_GEOSTD8", b't'),
    ("_GREEK", b't'),
    ("_HEBREW", b't'),
    ("_HP8", b't'),
    ("_KEYBCS2", b't'),
    ("_KOI8R", b't'),
    ("_KOI8U", b't'),
    ("_LATIN1", b't'),
    ("_LATIN2", b't'),
    ("_LATIN5", b't'),
    ("_LATIN7", b't'),
    ("_MACCE", b't'),
    ("_MACROMAN", b't'),
    ("_SJIS", b't'),
    ("_SWE7", b't'),
    ("_TIS620", b't'),
    ("_UJIS", b't'),
    ("_USC2", b't'),
    ("_UTF8", b't'),
    ("|/", b'o'),
    ("|=", b'o'),
    ("||", b'&'),
    ("~*", b'o'),
];
